### ISSUE TITLE
Implement Events Tracking System

### ISSUE THREAD

**Issue by flukeout** [mozilla/activate.mozilla.community#16]
In #8 we started work to adapt the Mozilla Clubs Events Reporter for Reps Events. Let's continue the work here...

**Links**
* [Clubs Events Tool](http://mozilla.github.io/clubs-events/)
* [Reps Evenst Tool Prototype](https://flukeout.github.io/reps-portal/)

**Questions**
* What site will this be linked from, can you please add a link?

**Work left to do**
* [ ] Change color palette to match new Reps site
* [ ] Change copy and wording to match new use-case
* [ ] Remove the stats at the top of the page that relate to countries & people
  * Should we leave just the event count?
  * Will leave event count and people
* [ ] Add a dropdown or some way to filter between the three main event types...
  * Rust Hack & Learn
  * Web Compatibility Sprint
  * Add ons.. 
* [ ] Finish creating the Google Form
  * Make sure all the questions are there and worded correctly
  * Set required fields if necessary
  * Change color scheme of form to match new site
* [ ] Figure out which repo this will be hosted in

cc @brianking @nukeador ...anything else?

Let's make sure we have a complete list of requirements in this issue. We can then estimate the work involved and time allowing, I can pitch in or at least point you all in the right direction.\

**Comment by brianking** [comment]
Luke, this looks right. A couple of things I would add are:

[] Rename project to activate-events
[] Change title to 'Activate Mozilla Events'

How much would you estimate for the work as listed now, and in what timeframe is it realistic in your schedule. If there is some low-hanging fruit I can jump in.

**Comment by brianking** [comment]
Campaign site: https://activate.mozilla.community

**Comment by brianking** [comment]
ON HOLD for now as per conversation in #8.

**Comment by brianking** [comment]
Hi @flukeout I'm going to close this off for now as we have decided to go with the Reps portal.

HUGE thank you for the help. I for one am a fan of this system, and we may very well use it for something else moving forward.

**Comment by flukeout** [comment]
You're welcome and best of luck with the campaign!
