### ISSUE TITLE
Update Roadmap

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/activate.mozilla.community#255]
- [x] The "Host a Techspeaker" activity should be moved to "now"
- [x] "Host a techspeaker" should be in the changelog with its correct date
- [x] Now should be Q2
- [x] Next should be Q3

**Comment by MichaelKohler** [comment]
I'll do this together with #268 as this requires a Roadmap update anyway.
