### ISSUE TITLE
Create Metrics Tracking Dashboard

### ISSUE THREAD

**Issue by brianking** [mozilla/activate.mozilla.community#47]
The metrics are listed in the activities, and the overall ones of the campaign in the FAQ. We need to ensure now that we are tracking correctly.

This issue is to:
- [x] Create the spreadsheet
- [ ] Add in initial numbers
- [ ] Equations! (with help from @couci)
- [ ] Dashboard visuals v0.1 (with help from @couci)
- [ ] Ensure we can track over time

**Comment by brianking** [comment]
https://docs.google.com/spreadsheets/d/1ss3nkmIIYYFLjvBfROB8-p2xB4HRAVTm5t323e_vhsk/edit

WIP - not much data there yet ... chasing it down.

**Comment by brianking** [comment]
We can see some metrics in Kibana, by filtering Reps Activities->MozActivate.

@mermi has also been playing around recently, and created this dashboard:
https://analytics.mozilla.community/goto/1885e80ab59921394642da4a46381c99

**Comment by brianking** [comment]
Issues:

https://github.com/mozilla/participation-metrics-org/labels/MozActivate

... based on these user stories:

https://docs.google.com/a/mozilla.com/document/d/1kcKbjnC0kWZFLhbA_0kFL1YCtqd61mEg9UNBbsjjpyA/edit?usp=sharing

**Comment by MichaelKohler** [comment]
There is a dashboard in Community Analytics now. If we need anything else, we can open a specific issue in the CD repo.
